# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04fa8bfb31da44901b356c0a81923847188c09388a1e431a9afafd6dec2c87a2f756bb573b914220ede0294f0167f092a514c40c5a7218bd0ddddd06764abc99

test:
  secret_key_base: 39b9cf593a27458e55a7b3fedf4d7a8c428399cbcf4d65efd33b09138c61dbfd68e3f961d2cbbd66a9cb2445877a23d1c299c01863f5c2b315a5e7c0fd7a1886

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
